version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgresql_materialized_view
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ledger_sync
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
#  mysql:
#    image: mysql:latest
#    container_name: mysql_db
#    environment:
#      MYSQL_ROOT_PASSWORD: 123456
#      MYSQL_DATABASE: yaci_store
#      MYSQL_USER: user
#      MYSQL_PASSWORD: 123456
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
volumes:
  postgres_data:
#  mysql_data: