name: Build and Upload Yaci Store Zip

on:
  workflow_dispatch:

jobs:
  windowBuild:
    strategy:
      matrix:
        profile: ["n2c", ""]
    runs-on: windows-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: '21.0.4'
          native-image-job-reports: 'true'
      - name: Extract version (Windows)
        shell: pwsh
        run: |
          $VERSION = (Get-Content gradle.properties | Where-Object { $_ -match "^version=" } | ForEach-Object { $_.Split('=')[1].Trim() })
          echo "VERSION=$VERSION" >> $env:GITHUB_ENV
      - name: Set Profile Suffix
        shell: pwsh
        run: |
          if ( "${{ matrix.profile }}" -ne "") {
            echo "PROFILE_SUFFIX=-${{ matrix.profile }}" >> $GITHUB_ENV
          } else {
            echo "PROFILE_SUFFIX=" >> $GITHUB_ENV
          }
          echo "${{  matrix.profile }}"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Windows specific env
        run: |
          echo "os_prefix=win" >> $GITHUB_ENV
          copy applications\all\src\main\resources\META-INF\native-image\yaci-store-all\native-image.properties.win applications\all\src\main\resources\META-INF\native-image\yaci-store-all\native-image.properties
      - name: Set lowercase architecture
        run: echo "arch=$(echo ${{ runner.arch }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Build with Gradle
        run: ./gradlew --no-daemon -i  -Pprofile=${{ matrix.profile }} clean cliZip
      - name: Copy artifacts
        run: mv applications/all/build/output/yaci-store-*.zip applications/all/build/output/yaci-store-${{ env.VERSION }}-${{ env.os_prefix }}-${{ env.arch }}${{ env.PROFILE_SUFFIX }}.zip
      - uses: actions/upload-artifact@v4
        with:
          name: yaci-store-${{ env.VERSION }}-${{ env.os_prefix }}-${{ env.arch }}${{ env.PROFILE_SUFFIX }}
          path: ./applications/all/build/output/yaci-store-${{ env.VERSION }}-${{ env.os_prefix }}-${{ env.arch }}${{ env.PROFILE_SUFFIX }}.zip
